"$schema" = 'https://starship.rs/config-schema.json'

format = """
$aws$gcloud$kubernetes
ü¶ô $all"""

add_newline = true

[character]
success_symbol = "[‚Üí](bold green)"
error_symbol   = "[‚Üí](bold red)"

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[aws]
format = '[$symbol($profile )(\($region\) )(\[$duration\] )]($style)'
[aws.region_aliases]
"ap-northeast-1" = "an1"

[gcloud]
format = '[$symbol$account @ $project / $region]($style) '
[gcloud.region_aliases]
"us-central1" = "uc1"
"asia-northeast1" = "an1"

[kubernetes]
format = '[üõ≥Ô∏è  $context \($namespace\)](black) '
disabled = false

[kubernetes.context_aliases]
# GCP GKE
"gke_(?P<project>[\\w-]+)_(?P<region>[\\w-]+)_(?P<cluster>[\\w-]+)" = "GKE:$cluster @ $project / $region"
# AWS EKS
# arn:aws:eks:ap-northeast-1:731842720035:cluster/sandbox
"arn:aws:eks:(?P<region>[\\w-]+):(?P<account>[\\w-]+):cluster/(?P<cluster>[\\w-]+)" = "EKS:$cluster @ $account / $region"
